import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  abstractionsSidebar: [{type: 'autogenerated', dirName: 'abstractions'}],
};

export default sidebars;
