import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  abstractionsSidebar: [{type: 'autogenerated', dirName: 'Abstractions'}],
  awexpectSidebar: [{type: 'autogenerated', dirName: 'aweXpect'}],
  mockolateSidebar: [{type: 'autogenerated', dirName: 'Mockolate'}],
  extensionsSidebar: [{type: 'autogenerated', dirName: 'Extensions'}],
  chronologySidebar: [{type: 'autogenerated', dirName: 'Chronology'}],
};

export default sidebars;
