import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  abstractionsSidebar: [{type: 'autogenerated', dirName: 'abstractions'}],
  awexpectSidebar: [{type: 'autogenerated', dirName: 'awexpect'}],
  mockolateSidebar: [{type: 'autogenerated', dirName: 'mockolate'}],
  extensionsSidebar: [{type: 'autogenerated', dirName: 'extensions'}],
  chronologySidebar: [{type: 'autogenerated', dirName: 'chronology'}],
};

export default sidebars;
